services:
  seqism-gateway:
    build: ./seqism-gateway
    container_name: seqism-gateway
    ports:
      - "8080:8080"
    depends_on:
      seqism-mq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=seqism-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  seqism-core:
    build: ./seqism-core
    container_name: seqism-core
    depends_on:
      seqism-mq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=seqism-mq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  seqism-mq:
    image: "rabbitmq:3-management"
    container_name: seqism-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5


