spring:
  rabbitmq:
    host: seqism-mq
    port: 5672
    username: guest
    password: guest

seqism:
  queue:
    static:
      name: seqism-static-queue
    command:
      prefix: seqism-command-queue.
    response:
      prefix: seqism-response-queue.